_extends: .github

repository:
  name: schema
  description: 📃 Standarized project metadata to specify the components, constructs and authorship of software
  topics: colophon, schema
  homepage: https://colophon.id
  has_issues: true
