version: 1.0.0

about:
  id: colophon-schema
  title: Colphon Schema
  description: Standarized project metadata to specify the components, constructs and authorship of software.

contacts:
  humans: Ahmad Nassri <hi@ahmad.codes>

schedule:
  launch: 2018-05-24T05:00:00.000Z

environments:
  - type: git
    title: Source Code
    uri: https://github.com/ahmadnassri/colophon

references:
  - title: Documentation
    uri: https://github.com/ahmadnassri/colophon
