version: 2.0

id: colophon-schema

about:
  title: Colphon Schema
  description: Schema for Colophon

contacts:
  - type: author
    name: Ahmad Nassri
    email: ahmad@codeinchaos.com

schedule:
  launch: 2018-05-24T05:00:00.000Z

environments:
  - type: git
    title: Source Code
    uri: https://github.com/ahmadnassri/colophon

references:
  - title: Documentation
    uri: https://github.com/ahmadnassri/colophon
